# Generated by Django 5.2.8 on 2026-03-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='published_at',
            field=models.DateTimeField(),
        ),
    ]
