# Generated by Django 5.2.8 on 2026-03-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_alter_notice_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='published_at',
            field=models.DateField(),
        ),
    ]
