# Generated by Django 5.2.8 on 2026-03-16 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_faculty_bcs_batch_faculty_email_faculty_facebook_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={},
        ),
    ]
