# Generated by Django 5.2.8 on 2026-03-16 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_faculty_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='facebook',
        ),
    ]
