# Generated by Django 5.2.8 on 2026-03-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_remove_faculty_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
    ]
