# Generated by Django 6.0.2 on 2026-02-25 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VicePrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(default='Vice Principal', max_length=100)),
                ('gov_id', models.CharField(blank=True, max_length=50, null=True)),
                ('bcs_batch', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vice_principal/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VicePostingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=255)),
                ('joining_date', models.DateField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('vice_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='administration.viceprincipal')),
            ],
            options={
                'ordering': ['-joining_date'],
            },
        ),
    ]
