# Generated by Django 6.0.2 on 2026-02-25 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_teacherscouncil_councilmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='AcademicCouncilMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='administration.academiccouncil')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
